// <auto-generated />
using System;
using Food.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Food.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.15")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Food.Entity.About", b =>
                {
                    b.Property<int>("about_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("about_Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("about_Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("about_Url")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("about_id");

                    b.ToTable("About");

                    b.HasData(
                        new
                        {
                            about_id = 1,
                            about_Description = "The Big Oxmox advised her not to do so, because there were thousands of bad Commas, wild Question Marks and devious Semikoli, but the Little Blind Text didn’t listen. She packed her seven versalia, put her initial into the belt and made herself on the way. \n \n When she reached the first hills of the Italic Mountains, she had a last view back on the skyline of her hometown Bookmarksgrove,the headline of Alphabet Village and the subline of her own road,the Line Lane.Pityful a rethoric question ran over her cheek,then she continued her way.",
                            about_Title = "Footwear the leading eCommerce Store around the Globe",
                            about_Url = "https://www.youtube.com/watch?v=F1vcruph8JA"
                        });
                });

            modelBuilder.Entity("Food.Entity.Bills", b =>
                {
                    b.Property<string>("bill_Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("bill_Cancelled")
                        .HasColumnType("bit");

                    b.Property<bool>("bill_Confirmation")
                        .HasColumnType("bit");

                    b.Property<DateTime>("bill_DatetimeOrder")
                        .HasColumnType("datetime2");

                    b.Property<bool>("bill_Delivered")
                        .HasColumnType("bit");

                    b.Property<bool>("bill_Delivering")
                        .HasColumnType("bit");

                    b.Property<int>("bill_Discount")
                        .HasColumnType("int");

                    b.Property<bool>("bill_HideStatus")
                        .HasColumnType("bit");

                    b.Property<string>("bill_Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("bill_PaidTotal")
                        .HasColumnType("int");

                    b.Property<string>("bill_PaymentMethod")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("bill_ProductColorlist")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("bill_ProductIdlist")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("bill_ProductNamelist")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("bill_ProductPricelist")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("bill_ProductSizelist")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("bill_Quantity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("bill_Shipping")
                        .HasColumnType("int");

                    b.Property<string>("bill_UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("bill_WaitForConfirmation")
                        .HasColumnType("bit");

                    b.Property<bool>("bill_WaitPickup")
                        .HasColumnType("bit");

                    b.HasKey("bill_Id");

                    b.HasIndex("bill_UserId");

                    b.ToTable("Bills");

                    b.HasData(
                        new
                        {
                            bill_Id = "D269BF93-A5E2-4C4A-8146-9967DDE80D30",
                            bill_Cancelled = false,
                            bill_Confirmation = true,
                            bill_DatetimeOrder = new DateTime(2022, 11, 27, 2, 45, 5, 892, DateTimeKind.Local).AddTicks(6799),
                            bill_Delivered = false,
                            bill_Delivering = false,
                            bill_Discount = 0,
                            bill_HideStatus = false,
                            bill_Note = "",
                            bill_PaidTotal = 2000,
                            bill_PaymentMethod = "Check Payment",
                            bill_ProductIdlist = "1|2|3|4",
                            bill_ProductNamelist = "product 1|product 2| product 3| product 4|",
                            bill_ProductPricelist = "550|450|350|640|",
                            bill_Quantity = "1|1|2|1|",
                            bill_Shipping = 10,
                            bill_UserId = "f49e4348-718f-43e3-b1f6-6dc89c5Bb5ff",
                            bill_WaitForConfirmation = false,
                            bill_WaitPickup = false
                        });
                });

            modelBuilder.Entity("Food.Entity.Cart", b =>
                {
                    b.Property<string>("cart_Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("cart_UserID")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("cart_Id");

                    b.HasIndex("cart_UserID");

                    b.ToTable("Carts");

                    b.HasData(
                        new
                        {
                            cart_Id = "72309286-ECBB-4D20-AD95-2819D31E3400",
                            cart_UserID = "f49e4348-718f-43e3-b1f6-6dc89c5Bb5ff"
                        },
                        new
                        {
                            cart_Id = "D355458F-1DD3-4834-AA28-6DA34B6357FF",
                            cart_UserID = "DE544998-A3CC-4E12-ABB4-0642E57BD222"
                        });
                });

            modelBuilder.Entity("Food.Entity.CartsDevice", b =>
                {
                    b.Property<string>("cartd_Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("cartd_DeviceId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("cartd_Id");

                    b.HasIndex("cartd_DeviceId");

                    b.ToTable("CartsDevice");
                });

            modelBuilder.Entity("Food.Entity.Categories", b =>
                {
                    b.Property<string>("cg_Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("cg_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("cg_Sale")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("cg_Type")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("cg_Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            cg_Id = "bcbcac6e-1613-4349-9071-74f219b11fcd",
                            cg_Name = "Dry food",
                            cg_Sale = "",
                            cg_Type = ""
                        },
                        new
                        {
                            cg_Id = "a97f7f87-963d-41e1-b687-14f4ca482767",
                            cg_Name = "Food",
                            cg_Sale = "",
                            cg_Type = ""
                        },
                        new
                        {
                            cg_Id = "44d5aadc-8748-493c-a196-564bc46a4fa8",
                            cg_Name = "Drink",
                            cg_Sale = "",
                            cg_Type = ""
                        },
                        new
                        {
                            cg_Id = "63796846-bf7a-4c6a-9deb-db6b39c4654d",
                            cg_Name = "Banhmi",
                            cg_Sale = "",
                            cg_Type = ""
                        },
                        new
                        {
                            cg_Id = "8ef45d41-c181-4909-8f4a-a6ce8ab2b4f3",
                            cg_Name = "Snack",
                            cg_Sale = "",
                            cg_Type = ""
                        });
                });

            modelBuilder.Entity("Food.Entity.ContactSystem", b =>
                {
                    b.Property<string>("Contact_Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Contact_Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Contact_Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Contact_Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Contact_Phone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Contact_Id");

                    b.ToTable("ContactSystems");

                    b.HasData(
                        new
                        {
                            Contact_Id = "6a142956-f72c-4d40-b165-9c114b24dd94",
                            Contact_Address = "Huntsville, AL 35813, USA",
                            Contact_Description = "Prof Lord John Krebs provides a brief history of human food, from our remote ancestors 3 million years ago to the present day. By looking at the four great transitions in human food - cooking, agriculture, processing, and preservation - he considers a variety of questions, including why people like some kinds of foods and not others; how your senses contribute to flavor; the role of genetics in our likes and dislikes; and the differences in learning and culture around the world.",
                            Contact_Email = "support@foodshop.com ",
                            Contact_Phone = "021.343.7575"
                        });
                });

            modelBuilder.Entity("Food.Entity.ContactUsers", b =>
                {
                    b.Property<string>("cu_Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("cu_Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("cu_Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("cu_FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("cu_LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("cu_Subject")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("cu_Id");

                    b.ToTable("ContactUsers");

                    b.HasData(
                        new
                        {
                            cu_Id = "3d0fb745-85eb-4cad-9882-ba5235f24648",
                            cu_Description = "Description",
                            cu_Email = "Email",
                            cu_FirstName = "FirstName",
                            cu_LastName = "LastName",
                            cu_Subject = "Subject"
                        });
                });

            modelBuilder.Entity("Food.Entity.Coupons", b =>
                {
                    b.Property<string>("couponId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("couponCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("couponPrice")
                        .HasColumnType("int");

                    b.HasKey("couponId");

                    b.ToTable("Coupons");

                    b.HasData(
                        new
                        {
                            couponId = "bfce9f3b-3329-4b0a-a9a5-e10018196064",
                            couponCode = "code10",
                            couponPrice = 10
                        },
                        new
                        {
                            couponId = "e2ab5d45-ed40-40dc-b383-7842109858a6",
                            couponCode = "code50",
                            couponPrice = 50
                        });
                });

            modelBuilder.Entity("Food.Entity.Device", b =>
                {
                    b.Property<string>("deviceId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("deviceAddress1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("deviceAddress2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("deviceCity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("deviceCompanyName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("deviceCountry")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("deviceName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("devicePhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("devicePostalCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("deviceState")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("deviceId");

                    b.ToTable("Device");
                });

            modelBuilder.Entity("Food.Entity.ProductInCart", b =>
                {
                    b.Property<string>("pic_CartId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("pic_ProductId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("pic_amount")
                        .HasColumnType("int");

                    b.Property<string>("pic_color")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pic_size")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("pic_CartId", "pic_ProductId");

                    b.HasIndex("pic_ProductId");

                    b.ToTable("ProductInCart");
                });

            modelBuilder.Entity("Food.Entity.ProductInCartDevices", b =>
                {
                    b.Property<string>("picd_CartId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("picd_ProductId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("picd_amount")
                        .HasColumnType("int");

                    b.Property<string>("picd_color")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("picd_size")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("picd_CartId", "picd_ProductId");

                    b.HasIndex("picd_ProductId");

                    b.ToTable("ProductInCartDevices");
                });

            modelBuilder.Entity("Food.Entity.Products", b =>
                {
                    b.Property<string>("pd_Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("isDelete")
                        .HasColumnType("bit");

                    b.Property<string>("pd_Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pd_Img1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pd_Img2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pd_Img3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pd_Img4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pd_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pd_NameImg1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pd_NameImg2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pd_NameImg3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pd_NameImg4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("pd_Price")
                        .HasColumnType("int");

                    b.Property<int>("pd_Rate")
                        .HasColumnType("int");

                    b.Property<int>("pd_ReducePrice")
                        .HasColumnType("int");

                    b.Property<string>("pd_ShortDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("pd_WaitForConfirmation")
                        .HasColumnType("bit");

                    b.HasKey("pd_Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            pd_Id = "d8a2d956-e131-4ba7-b8c9-f3618db454cf",
                            isDelete = false,
                            pd_Description = "BanhCanhCua",
                            pd_Img1 = "/images/item250x300/BanhCanhCua.png",
                            pd_Img2 = "",
                            pd_Img3 = "",
                            pd_Img4 = "",
                            pd_Name = "BanhCanhCua",
                            pd_NameImg1 = "1",
                            pd_NameImg2 = "2",
                            pd_NameImg3 = "3",
                            pd_NameImg4 = "4",
                            pd_Price = 1,
                            pd_Rate = 5,
                            pd_ReducePrice = 0,
                            pd_ShortDescription = "Short Description",
                            pd_WaitForConfirmation = false
                        },
                        new
                        {
                            pd_Id = "f3243d82-38ac-4c11-8cc0-1eff6a184c3a",
                            isDelete = false,
                            pd_Description = "BanhMi",
                            pd_Img1 = "/images/item250x300/BanhMi.png",
                            pd_Img2 = "",
                            pd_Img3 = "",
                            pd_Img4 = "",
                            pd_Name = "BanhMi",
                            pd_NameImg1 = "1",
                            pd_NameImg2 = "2",
                            pd_NameImg3 = "3",
                            pd_NameImg4 = "4",
                            pd_Price = 1,
                            pd_Rate = 5,
                            pd_ReducePrice = 0,
                            pd_ShortDescription = "Short Description",
                            pd_WaitForConfirmation = false
                        },
                        new
                        {
                            pd_Id = "9319e87b-e3d6-446f-9321-2772fee10ecf",
                            isDelete = false,
                            pd_Description = "banhtrangtron",
                            pd_Img1 = "/images/item250x300/banhtrangtron.png",
                            pd_Img2 = "",
                            pd_Img3 = "",
                            pd_Img4 = "",
                            pd_Name = "banhtrangtron",
                            pd_NameImg1 = "1",
                            pd_NameImg2 = "2",
                            pd_NameImg3 = "3",
                            pd_NameImg4 = "4",
                            pd_Price = 1,
                            pd_Rate = 5,
                            pd_ReducePrice = 0,
                            pd_ShortDescription = "Short Description",
                            pd_WaitForConfirmation = false
                        },
                        new
                        {
                            pd_Id = "0862b11d-f6f6-4f25-a04b-c6bc8d5d3c4c",
                            isDelete = false,
                            pd_Description = "banhuotlongdalat",
                            pd_Img1 = "/images/item250x300/banhuotlongdalat.png",
                            pd_Img2 = "",
                            pd_Img3 = "",
                            pd_Img4 = "",
                            pd_Name = "banhuotlongdalat",
                            pd_NameImg1 = "1",
                            pd_NameImg2 = "2",
                            pd_NameImg3 = "3",
                            pd_NameImg4 = "4",
                            pd_Price = 1,
                            pd_Rate = 5,
                            pd_ReducePrice = 0,
                            pd_ShortDescription = "Short Description",
                            pd_WaitForConfirmation = false
                        },
                        new
                        {
                            pd_Id = "c9238727-a534-455e-bba1-8d8b7b0c194d",
                            isDelete = false,
                            pd_Description = "BoKho",
                            pd_Img1 = "/images/item250x300/BoKho.png",
                            pd_Img2 = "",
                            pd_Img3 = "",
                            pd_Img4 = "",
                            pd_Name = "BoKho",
                            pd_NameImg1 = "1",
                            pd_NameImg2 = "2",
                            pd_NameImg3 = "3",
                            pd_NameImg4 = "4",
                            pd_Price = 1,
                            pd_Rate = 5,
                            pd_ReducePrice = 0,
                            pd_ShortDescription = "Short Description",
                            pd_WaitForConfirmation = false
                        },
                        new
                        {
                            pd_Id = "68e7a3e3-ea4d-476c-ba1a-5ccd31b7b57e",
                            isDelete = false,
                            pd_Description = "bunbo",
                            pd_Img1 = "/images/item250x300/bunbo.png",
                            pd_Img2 = "",
                            pd_Img3 = "",
                            pd_Img4 = "",
                            pd_Name = "bunbo",
                            pd_NameImg1 = "1",
                            pd_NameImg2 = "2",
                            pd_NameImg3 = "3",
                            pd_NameImg4 = "4",
                            pd_Price = 1,
                            pd_Rate = 5,
                            pd_ReducePrice = 0,
                            pd_ShortDescription = "Short Description",
                            pd_WaitForConfirmation = false
                        },
                        new
                        {
                            pd_Id = "83786857-b5f7-43df-be9a-4a0a1e6d6545",
                            isDelete = false,
                            pd_Description = "bundaumamtom",
                            pd_Img1 = "/images/item250x300/bundaumamtom.png",
                            pd_Img2 = "",
                            pd_Img3 = "",
                            pd_Img4 = "",
                            pd_Name = "bundaumamtom",
                            pd_NameImg1 = "1",
                            pd_NameImg2 = "2",
                            pd_NameImg3 = "3",
                            pd_NameImg4 = "4",
                            pd_Price = 1,
                            pd_Rate = 5,
                            pd_ReducePrice = 0,
                            pd_ShortDescription = "Short Description",
                            pd_WaitForConfirmation = false
                        },
                        new
                        {
                            pd_Id = "709a36e3-6f18-4d9a-acdc-8ef0e3a51eca",
                            isDelete = false,
                            pd_Description = "Bunxaochay",
                            pd_Img1 = "/images/item250x300/Bunxaochay.png",
                            pd_Img2 = "",
                            pd_Img3 = "",
                            pd_Img4 = "",
                            pd_Name = "Bunxaochay",
                            pd_NameImg1 = "1",
                            pd_NameImg2 = "2",
                            pd_NameImg3 = "3",
                            pd_NameImg4 = "4",
                            pd_Price = 1,
                            pd_Rate = 5,
                            pd_ReducePrice = 0,
                            pd_ShortDescription = "Short Description",
                            pd_WaitForConfirmation = false
                        },
                        new
                        {
                            pd_Id = "1fac924d-ad24-47c4-95ef-897f9b917083",
                            isDelete = false,
                            pd_Description = "cocosummer",
                            pd_Img1 = "/images/item250x300/cocosummer.png",
                            pd_Img2 = "",
                            pd_Img3 = "",
                            pd_Img4 = "",
                            pd_Name = "cocosummer",
                            pd_NameImg1 = "1",
                            pd_NameImg2 = "2",
                            pd_NameImg3 = "3",
                            pd_NameImg4 = "4",
                            pd_Price = 1,
                            pd_Rate = 5,
                            pd_ReducePrice = 0,
                            pd_ShortDescription = "Short Description",
                            pd_WaitForConfirmation = false
                        },
                        new
                        {
                            pd_Id = "3c4cc2d5-e9c6-46a3-b253-480889782277",
                            isDelete = false,
                            pd_Description = "comboxao",
                            pd_Img1 = "/images/item250x300/comboxao.png",
                            pd_Img2 = "",
                            pd_Img3 = "",
                            pd_Img4 = "",
                            pd_Name = "comboxao",
                            pd_NameImg1 = "1",
                            pd_NameImg2 = "2",
                            pd_NameImg3 = "3",
                            pd_NameImg4 = "4",
                            pd_Price = 1,
                            pd_Rate = 5,
                            pd_ReducePrice = 0,
                            pd_ShortDescription = "Short Description",
                            pd_WaitForConfirmation = false
                        },
                        new
                        {
                            pd_Id = "60c392a9-d080-4d71-9870-b10a7993ad57",
                            isDelete = false,
                            pd_Description = "comga",
                            pd_Img1 = "/images/item250x300/comga.png",
                            pd_Img2 = "",
                            pd_Img3 = "",
                            pd_Img4 = "",
                            pd_Name = "comga",
                            pd_NameImg1 = "1",
                            pd_NameImg2 = "2",
                            pd_NameImg3 = "3",
                            pd_NameImg4 = "4",
                            pd_Price = 1,
                            pd_Rate = 5,
                            pd_ReducePrice = 0,
                            pd_ShortDescription = "Short Description",
                            pd_WaitForConfirmation = false
                        },
                        new
                        {
                            pd_Id = "bc68ceff-46c6-4ed9-a8d4-53d704c51cd8",
                            isDelete = false,
                            pd_Description = "comgadenhat",
                            pd_Img1 = "/images/item250x300/comgadenhat.png",
                            pd_Img2 = "",
                            pd_Img3 = "",
                            pd_Img4 = "",
                            pd_Name = "comgadenhat",
                            pd_NameImg1 = "1",
                            pd_NameImg2 = "2",
                            pd_NameImg3 = "3",
                            pd_NameImg4 = "4",
                            pd_Price = 1,
                            pd_Rate = 5,
                            pd_ReducePrice = 0,
                            pd_ShortDescription = "Short Description",
                            pd_WaitForConfirmation = false
                        },
                        new
                        {
                            pd_Id = "358dc2d8-4aee-488a-b194-be37796cbdbb",
                            isDelete = false,
                            pd_Description = "denhatthitnuong",
                            pd_Img1 = "/images/item250x300/denhatthitnuong.png",
                            pd_Img2 = "",
                            pd_Img3 = "",
                            pd_Img4 = "",
                            pd_Name = "denhatthitnuong",
                            pd_NameImg1 = "1",
                            pd_NameImg2 = "2",
                            pd_NameImg3 = "3",
                            pd_NameImg4 = "4",
                            pd_Price = 1,
                            pd_Rate = 5,
                            pd_ReducePrice = 0,
                            pd_ShortDescription = "Short Description",
                            pd_WaitForConfirmation = false
                        },
                        new
                        {
                            pd_Id = "757f430e-5cc6-4396-8513-475310e71600",
                            isDelete = false,
                            pd_Description = "goicuon",
                            pd_Img1 = "/images/item250x300/goicuon.png",
                            pd_Img2 = "",
                            pd_Img3 = "",
                            pd_Img4 = "",
                            pd_Name = "goicuon",
                            pd_NameImg1 = "1",
                            pd_NameImg2 = "2",
                            pd_NameImg3 = "3",
                            pd_NameImg4 = "4",
                            pd_Price = 1,
                            pd_Rate = 5,
                            pd_ReducePrice = 0,
                            pd_ShortDescription = "Short Description",
                            pd_WaitForConfirmation = false
                        },
                        new
                        {
                            pd_Id = "65ba2c6a-4fc5-4dd6-8720-3b74c8085acf",
                            isDelete = false,
                            pd_Description = "kfc",
                            pd_Img1 = "/images/item250x300/kfc.png",
                            pd_Img2 = "",
                            pd_Img3 = "",
                            pd_Img4 = "",
                            pd_Name = "kfc",
                            pd_NameImg1 = "1",
                            pd_NameImg2 = "2",
                            pd_NameImg3 = "3",
                            pd_NameImg4 = "4",
                            pd_Price = 1,
                            pd_Rate = 5,
                            pd_ReducePrice = 0,
                            pd_ShortDescription = "Short Description",
                            pd_WaitForConfirmation = false
                        },
                        new
                        {
                            pd_Id = "c9041cda-b283-4718-a11a-4dfb5ca268cc",
                            isDelete = false,
                            pd_Description = "KimBap",
                            pd_Img1 = "/images/item250x300/KimBap.png",
                            pd_Img2 = "",
                            pd_Img3 = "",
                            pd_Img4 = "",
                            pd_Name = "KimBap",
                            pd_NameImg1 = "1",
                            pd_NameImg2 = "2",
                            pd_NameImg3 = "3",
                            pd_NameImg4 = "4",
                            pd_Price = 1,
                            pd_Rate = 5,
                            pd_ReducePrice = 0,
                            pd_ShortDescription = "Short Description",
                            pd_WaitForConfirmation = false
                        },
                        new
                        {
                            pd_Id = "4a5ef2cc-1466-493b-b577-51bdaf93fbfd",
                            isDelete = false,
                            pd_Description = "loteria",
                            pd_Img1 = "/images/item250x300/loteria.png",
                            pd_Img2 = "",
                            pd_Img3 = "",
                            pd_Img4 = "",
                            pd_Name = "loteria",
                            pd_NameImg1 = "1",
                            pd_NameImg2 = "2",
                            pd_NameImg3 = "3",
                            pd_NameImg4 = "4",
                            pd_Price = 1,
                            pd_Rate = 5,
                            pd_ReducePrice = 0,
                            pd_ShortDescription = "Short Description",
                            pd_WaitForConfirmation = false
                        },
                        new
                        {
                            pd_Id = "a743af33-dc85-4ea1-91f2-734fdffa0515",
                            isDelete = false,
                            pd_Description = "mitronanvat",
                            pd_Img1 = "/images/item250x300/mitronanvat.png",
                            pd_Img2 = "",
                            pd_Img3 = "",
                            pd_Img4 = "",
                            pd_Name = "mitronanvat",
                            pd_NameImg1 = "1",
                            pd_NameImg2 = "2",
                            pd_NameImg3 = "3",
                            pd_NameImg4 = "4",
                            pd_Price = 1,
                            pd_Rate = 5,
                            pd_ReducePrice = 0,
                            pd_ShortDescription = "Short Description",
                            pd_WaitForConfirmation = false
                        },
                        new
                        {
                            pd_Id = "f34bef58-8038-46ec-926a-6358affdea02",
                            isDelete = false,
                            pd_Description = "monngontrangbang",
                            pd_Img1 = "/images/item250x300/monngontrangbang.png",
                            pd_Img2 = "",
                            pd_Img3 = "",
                            pd_Img4 = "",
                            pd_Name = "monngontrangbang",
                            pd_NameImg1 = "1",
                            pd_NameImg2 = "2",
                            pd_NameImg3 = "3",
                            pd_NameImg4 = "4",
                            pd_Price = 1,
                            pd_Rate = 5,
                            pd_ReducePrice = 0,
                            pd_ShortDescription = "Short Description",
                            pd_WaitForConfirmation = false
                        },
                        new
                        {
                            pd_Id = "6a00ead5-43ca-47b8-b0b0-b678c980be93",
                            isDelete = false,
                            pd_Description = "ParisBaguete",
                            pd_Img1 = "/images/item250x300/ParisBaguete.png",
                            pd_Img2 = "",
                            pd_Img3 = "",
                            pd_Img4 = "",
                            pd_Name = "ParisBaguete",
                            pd_NameImg1 = "1",
                            pd_NameImg2 = "2",
                            pd_NameImg3 = "3",
                            pd_NameImg4 = "4",
                            pd_Price = 1,
                            pd_Rate = 5,
                            pd_ReducePrice = 0,
                            pd_ShortDescription = "Short Description",
                            pd_WaitForConfirmation = false
                        },
                        new
                        {
                            pd_Id = "e696b34b-760b-454a-b8de-c5642dcc6028",
                            isDelete = false,
                            pd_Description = "pizza",
                            pd_Img1 = "/images/item250x300/pizza.png",
                            pd_Img2 = "",
                            pd_Img3 = "",
                            pd_Img4 = "",
                            pd_Name = "pizza",
                            pd_NameImg1 = "1",
                            pd_NameImg2 = "2",
                            pd_NameImg3 = "3",
                            pd_NameImg4 = "4",
                            pd_Price = 1,
                            pd_Rate = 5,
                            pd_ReducePrice = 0,
                            pd_ShortDescription = "Short Description",
                            pd_WaitForConfirmation = false
                        },
                        new
                        {
                            pd_Id = "3660a0cd-89fe-4593-aac3-d91731cf7e09",
                            isDelete = false,
                            pd_Description = "quanngontrangbang",
                            pd_Img1 = "/images/item250x300/quanngontrangbang.png",
                            pd_Img2 = "",
                            pd_Img3 = "",
                            pd_Img4 = "",
                            pd_Name = "quanngontrangbang",
                            pd_NameImg1 = "1",
                            pd_NameImg2 = "2",
                            pd_NameImg3 = "3",
                            pd_NameImg4 = "4",
                            pd_Price = 1,
                            pd_Rate = 5,
                            pd_ReducePrice = 0,
                            pd_ShortDescription = "Short Description",
                            pd_WaitForConfirmation = false
                        },
                        new
                        {
                            pd_Id = "fcdb19e0-fed8-45f9-9a47-65687e1df300",
                            isDelete = false,
                            pd_Description = "RauMaMix",
                            pd_Img1 = "/images/item250x300/RauMaMix.png",
                            pd_Img2 = "",
                            pd_Img3 = "",
                            pd_Img4 = "",
                            pd_Name = "RauMaMix",
                            pd_NameImg1 = "1",
                            pd_NameImg2 = "2",
                            pd_NameImg3 = "3",
                            pd_NameImg4 = "4",
                            pd_Price = 1,
                            pd_Rate = 5,
                            pd_ReducePrice = 0,
                            pd_ShortDescription = "Short Description",
                            pd_WaitForConfirmation = false
                        },
                        new
                        {
                            pd_Id = "aca26047-4d29-4758-a99f-ce7fb358d446",
                            isDelete = false,
                            pd_Description = "Royaltea",
                            pd_Img1 = "/images/item250x300/Royaltea.png",
                            pd_Img2 = "",
                            pd_Img3 = "",
                            pd_Img4 = "",
                            pd_Name = "Royaltea",
                            pd_NameImg1 = "1",
                            pd_NameImg2 = "2",
                            pd_NameImg3 = "3",
                            pd_NameImg4 = "4",
                            pd_Price = 1,
                            pd_Rate = 5,
                            pd_ReducePrice = 0,
                            pd_ShortDescription = "Short Description",
                            pd_WaitForConfirmation = false
                        },
                        new
                        {
                            pd_Id = "556387d2-a023-4b2c-a209-9f7283b5969c",
                            isDelete = false,
                            pd_Description = "Sanfulou",
                            pd_Img1 = "/images/item250x300/Sanfulou.png",
                            pd_Img2 = "",
                            pd_Img3 = "",
                            pd_Img4 = "",
                            pd_Name = "Sanfulou",
                            pd_NameImg1 = "1",
                            pd_NameImg2 = "2",
                            pd_NameImg3 = "3",
                            pd_NameImg4 = "4",
                            pd_Price = 1,
                            pd_Rate = 5,
                            pd_ReducePrice = 0,
                            pd_ShortDescription = "Short Description",
                            pd_WaitForConfirmation = false
                        },
                        new
                        {
                            pd_Id = "d3a499a3-3d8a-4371-bb15-a13971e7fbe3",
                            isDelete = false,
                            pd_Description = "stacbuk-cf",
                            pd_Img1 = "/images/item250x300/stacbuk-cf.png",
                            pd_Img2 = "",
                            pd_Img3 = "",
                            pd_Img4 = "",
                            pd_Name = "stacbuk-cf",
                            pd_NameImg1 = "1",
                            pd_NameImg2 = "2",
                            pd_NameImg3 = "3",
                            pd_NameImg4 = "4",
                            pd_Price = 1,
                            pd_Rate = 5,
                            pd_ReducePrice = 0,
                            pd_ShortDescription = "Short Description",
                            pd_WaitForConfirmation = false
                        },
                        new
                        {
                            pd_Id = "254ac966-0e9a-438b-8051-677b4d93bf4c",
                            isDelete = false,
                            pd_Description = "trasuanhalam",
                            pd_Img1 = "/images/item250x300/trasuanhalam.png",
                            pd_Img2 = "",
                            pd_Img3 = "",
                            pd_Img4 = "",
                            pd_Name = "trasuanhalam",
                            pd_NameImg1 = "1",
                            pd_NameImg2 = "2",
                            pd_NameImg3 = "3",
                            pd_NameImg4 = "4",
                            pd_Price = 1,
                            pd_Rate = 5,
                            pd_ReducePrice = 0,
                            pd_ShortDescription = "Short Description",
                            pd_WaitForConfirmation = false
                        },
                        new
                        {
                            pd_Id = "fe2d14f8-4804-445d-8b4b-9d61a48346f2",
                            isDelete = false,
                            pd_Description = "Xoixeoba3beo",
                            pd_Img1 = "/images/item250x300/Xoixeoba3beo.png",
                            pd_Img2 = "",
                            pd_Img3 = "",
                            pd_Img4 = "",
                            pd_Name = "Xoixeoba3beo",
                            pd_NameImg1 = "1",
                            pd_NameImg2 = "2",
                            pd_NameImg3 = "3",
                            pd_NameImg4 = "4",
                            pd_Price = 1,
                            pd_Rate = 5,
                            pd_ReducePrice = 0,
                            pd_ShortDescription = "Short Description",
                            pd_WaitForConfirmation = false
                        });
                });

            modelBuilder.Entity("Food.Entity.ProductsInCategories", b =>
                {
                    b.Property<string>("pic_productId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("pic_CategoriesId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("pic_productId", "pic_CategoriesId");

                    b.HasIndex("pic_CategoriesId");

                    b.ToTable("ProductsInCategories");

                    b.HasData(
                        new
                        {
                            pic_productId = "83786857-b5f7-43df-be9a-4a0a1e6d6545",
                            pic_CategoriesId = "bcbcac6e-1613-4349-9071-74f219b11fcd"
                        },
                        new
                        {
                            pic_productId = "709a36e3-6f18-4d9a-acdc-8ef0e3a51eca",
                            pic_CategoriesId = "bcbcac6e-1613-4349-9071-74f219b11fcd"
                        },
                        new
                        {
                            pic_productId = "3c4cc2d5-e9c6-46a3-b253-480889782277",
                            pic_CategoriesId = "bcbcac6e-1613-4349-9071-74f219b11fcd"
                        },
                        new
                        {
                            pic_productId = "60c392a9-d080-4d71-9870-b10a7993ad57",
                            pic_CategoriesId = "bcbcac6e-1613-4349-9071-74f219b11fcd"
                        },
                        new
                        {
                            pic_productId = "bc68ceff-46c6-4ed9-a8d4-53d704c51cd8",
                            pic_CategoriesId = "bcbcac6e-1613-4349-9071-74f219b11fcd"
                        },
                        new
                        {
                            pic_productId = "358dc2d8-4aee-488a-b194-be37796cbdbb",
                            pic_CategoriesId = "bcbcac6e-1613-4349-9071-74f219b11fcd"
                        },
                        new
                        {
                            pic_productId = "757f430e-5cc6-4396-8513-475310e71600",
                            pic_CategoriesId = "bcbcac6e-1613-4349-9071-74f219b11fcd"
                        },
                        new
                        {
                            pic_productId = "c9041cda-b283-4718-a11a-4dfb5ca268cc",
                            pic_CategoriesId = "bcbcac6e-1613-4349-9071-74f219b11fcd"
                        },
                        new
                        {
                            pic_productId = "d8a2d956-e131-4ba7-b8c9-f3618db454cf",
                            pic_CategoriesId = "a97f7f87-963d-41e1-b687-14f4ca482767"
                        },
                        new
                        {
                            pic_productId = "0862b11d-f6f6-4f25-a04b-c6bc8d5d3c4c",
                            pic_CategoriesId = "a97f7f87-963d-41e1-b687-14f4ca482767"
                        },
                        new
                        {
                            pic_productId = "c9238727-a534-455e-bba1-8d8b7b0c194d",
                            pic_CategoriesId = "a97f7f87-963d-41e1-b687-14f4ca482767"
                        },
                        new
                        {
                            pic_productId = "68e7a3e3-ea4d-476c-ba1a-5ccd31b7b57e",
                            pic_CategoriesId = "a97f7f87-963d-41e1-b687-14f4ca482767"
                        },
                        new
                        {
                            pic_productId = "f34bef58-8038-46ec-926a-6358affdea02",
                            pic_CategoriesId = "a97f7f87-963d-41e1-b687-14f4ca482767"
                        },
                        new
                        {
                            pic_productId = "fcdb19e0-fed8-45f9-9a47-65687e1df300",
                            pic_CategoriesId = "44d5aadc-8748-493c-a196-564bc46a4fa8"
                        },
                        new
                        {
                            pic_productId = "aca26047-4d29-4758-a99f-ce7fb358d446",
                            pic_CategoriesId = "44d5aadc-8748-493c-a196-564bc46a4fa8"
                        },
                        new
                        {
                            pic_productId = "d3a499a3-3d8a-4371-bb15-a13971e7fbe3",
                            pic_CategoriesId = "44d5aadc-8748-493c-a196-564bc46a4fa8"
                        },
                        new
                        {
                            pic_productId = "254ac966-0e9a-438b-8051-677b4d93bf4c",
                            pic_CategoriesId = "44d5aadc-8748-493c-a196-564bc46a4fa8"
                        },
                        new
                        {
                            pic_productId = "f3243d82-38ac-4c11-8cc0-1eff6a184c3a",
                            pic_CategoriesId = "63796846-bf7a-4c6a-9deb-db6b39c4654d"
                        },
                        new
                        {
                            pic_productId = "a743af33-dc85-4ea1-91f2-734fdffa0515",
                            pic_CategoriesId = "63796846-bf7a-4c6a-9deb-db6b39c4654d"
                        },
                        new
                        {
                            pic_productId = "9319e87b-e3d6-446f-9321-2772fee10ecf",
                            pic_CategoriesId = "8ef45d41-c181-4909-8f4a-a6ce8ab2b4f3"
                        },
                        new
                        {
                            pic_productId = "1fac924d-ad24-47c4-95ef-897f9b917083",
                            pic_CategoriesId = "8ef45d41-c181-4909-8f4a-a6ce8ab2b4f3"
                        },
                        new
                        {
                            pic_productId = "65ba2c6a-4fc5-4dd6-8720-3b74c8085acf",
                            pic_CategoriesId = "8ef45d41-c181-4909-8f4a-a6ce8ab2b4f3"
                        },
                        new
                        {
                            pic_productId = "4a5ef2cc-1466-493b-b577-51bdaf93fbfd",
                            pic_CategoriesId = "8ef45d41-c181-4909-8f4a-a6ce8ab2b4f3"
                        },
                        new
                        {
                            pic_productId = "6a00ead5-43ca-47b8-b0b0-b678c980be93",
                            pic_CategoriesId = "8ef45d41-c181-4909-8f4a-a6ce8ab2b4f3"
                        },
                        new
                        {
                            pic_productId = "e696b34b-760b-454a-b8de-c5642dcc6028",
                            pic_CategoriesId = "8ef45d41-c181-4909-8f4a-a6ce8ab2b4f3"
                        },
                        new
                        {
                            pic_productId = "3660a0cd-89fe-4593-aac3-d91731cf7e09",
                            pic_CategoriesId = "8ef45d41-c181-4909-8f4a-a6ce8ab2b4f3"
                        },
                        new
                        {
                            pic_productId = "556387d2-a023-4b2c-a209-9f7283b5969c",
                            pic_CategoriesId = "8ef45d41-c181-4909-8f4a-a6ce8ab2b4f3"
                        },
                        new
                        {
                            pic_productId = "fe2d14f8-4804-445d-8b4b-9d61a48346f2",
                            pic_CategoriesId = "8ef45d41-c181-4909-8f4a-a6ce8ab2b4f3"
                        });
                });

            modelBuilder.Entity("Food.Entity.ReviewInproduct", b =>
                {
                    b.Property<string>("rip_ProductId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("rip_ReviewId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("rip_ProductId", "rip_ReviewId");

                    b.HasIndex("rip_ReviewId");

                    b.ToTable("ReviewInproduct");

                    b.HasData(
                        new
                        {
                            rip_ProductId = "d8a2d956-e131-4ba7-b8c9-f3618db454cf",
                            rip_ReviewId = "EEBA6608-AB75-4E83-909F-604B1A06F16C"
                        },
                        new
                        {
                            rip_ProductId = "d8a2d956-e131-4ba7-b8c9-f3618db454cf",
                            rip_ReviewId = "9EED8607-D2BB-45EE-AEE3-C59D858A7F97"
                        },
                        new
                        {
                            rip_ProductId = "d8a2d956-e131-4ba7-b8c9-f3618db454cf",
                            rip_ReviewId = "C2A543C2-B1E2-4DC5-A131-9137E4673FA6"
                        });
                });

            modelBuilder.Entity("Food.Entity.Reviews", b =>
                {
                    b.Property<string>("review_id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("review_Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("review_HideStatus")
                        .HasColumnType("bit");

                    b.Property<string>("review_ReviewType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("review_UploadTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("review_UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("review_id");

                    b.HasIndex("review_UserId");

                    b.ToTable("Reviews");

                    b.HasData(
                        new
                        {
                            review_id = "EEBA6608-AB75-4E83-909F-604B1A06F16C",
                            review_Comment = "Good1",
                            review_HideStatus = false,
                            review_ReviewType = "Review",
                            review_UploadTime = new DateTime(2020, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            review_UserId = "DE544998-A3CC-4E12-ABB4-0642E57BD222"
                        },
                        new
                        {
                            review_id = "9EED8607-D2BB-45EE-AEE3-C59D858A7F97",
                            review_Comment = "Good2",
                            review_HideStatus = false,
                            review_ReviewType = "Review",
                            review_UploadTime = new DateTime(2020, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            review_UserId = "f49e4348-718f-43e3-b1f6-6dc89c5Bb5ff"
                        },
                        new
                        {
                            review_id = "C2A543C2-B1E2-4DC5-A131-9137E4673FA6",
                            review_Comment = "Good3",
                            review_HideStatus = false,
                            review_ReviewType = "Review",
                            review_UploadTime = new DateTime(2020, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            review_UserId = "DE544998-A3CC-4E12-ABB4-0642E57BD222"
                        });
                });

            modelBuilder.Entity("Food.Entity.Shipping", b =>
                {
                    b.Property<string>("ship_Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ship_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ship_Price")
                        .HasColumnType("int");

                    b.HasKey("ship_Id");

                    b.ToTable("Shipping");

                    b.HasData(
                        new
                        {
                            ship_Id = "7CF94A7D-9239-446E-A404-086518F84652",
                            ship_Name = "Ship",
                            ship_Price = 5
                        });
                });

            modelBuilder.Entity("Food.Entity.SubReview", b =>
                {
                    b.Property<string>("subReview_Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("subReview_Commnet")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("subReview_DateCommnet")
                        .HasColumnType("datetime2");

                    b.Property<bool>("subReview_HideStatus")
                        .HasColumnType("bit");

                    b.Property<string>("subReview_UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("subreview_SubReviewType")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("subReview_Id");

                    b.HasIndex("subReview_UserId");

                    b.ToTable("SubReview");

                    b.HasData(
                        new
                        {
                            subReview_Id = "90c6217f-92fb-452c-90d2-0e4574aa5d7e",
                            subReview_Commnet = "subreview 1",
                            subReview_DateCommnet = new DateTime(2020, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            subReview_HideStatus = false,
                            subReview_UserId = "DE544998-A3CC-4E12-ABB4-0642E57BD222",
                            subreview_SubReviewType = "SubReview"
                        },
                        new
                        {
                            subReview_Id = "a6d2e179-92e6-417b-92d6-35e50deb0782",
                            subReview_Commnet = "subreview 3",
                            subReview_DateCommnet = new DateTime(2020, 1, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            subReview_HideStatus = false,
                            subReview_UserId = "f49e4348-718f-43e3-b1f6-6dc89c5Bb5ff",
                            subreview_SubReviewType = "SubReview"
                        },
                        new
                        {
                            subReview_Id = "2a75ab7d-7122-471c-a489-a940956b78cb",
                            subReview_Commnet = "subreview 3",
                            subReview_DateCommnet = new DateTime(2020, 1, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            subReview_HideStatus = false,
                            subReview_UserId = "DE544998-A3CC-4E12-ABB4-0642E57BD222",
                            subreview_SubReviewType = "SubReview"
                        });
                });

            modelBuilder.Entity("Food.Entity.SubReviewInReview", b =>
                {
                    b.Property<string>("SRiR_ReviewId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("SRiR_SubReviewId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("SRiR_ReviewId", "SRiR_SubReviewId");

                    b.HasIndex("SRiR_SubReviewId");

                    b.ToTable("SubReviewInReview");

                    b.HasData(
                        new
                        {
                            SRiR_ReviewId = "EEBA6608-AB75-4E83-909F-604B1A06F16C",
                            SRiR_SubReviewId = "90c6217f-92fb-452c-90d2-0e4574aa5d7e"
                        },
                        new
                        {
                            SRiR_ReviewId = "EEBA6608-AB75-4E83-909F-604B1A06F16C",
                            SRiR_SubReviewId = "a6d2e179-92e6-417b-92d6-35e50deb0782"
                        },
                        new
                        {
                            SRiR_ReviewId = "9EED8607-D2BB-45EE-AEE3-C59D858A7F97",
                            SRiR_SubReviewId = "2a75ab7d-7122-471c-a489-a940956b78cb"
                        });
                });

            modelBuilder.Entity("Food.Entity.SubscribeEmail", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SubscribeEmail");
                });

            modelBuilder.Entity("Food.Models.UserInRoleModel", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameRole")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("UserInRoleModel");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("Roles");

                    b.HasDiscriminator<string>("Discriminator").HasValue("IdentityRole");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("RoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("Users");

                    b.HasDiscriminator<string>("Discriminator").HasValue("IdentityUser");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("UserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles");

                    b.HasData(
                        new
                        {
                            UserId = "f49e4348-718f-43e3-b1f6-6dc89c5Bb5ff",
                            RoleId = "f49e4348-718f-43e3-b1f6-6dc89c5Bb4fd"
                        },
                        new
                        {
                            UserId = "DE544998-A3CC-4E12-ABB4-0642E57BD222",
                            RoleId = "360E601E-92F2-4F08-832B-604A21293258"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("UserTokens");
                });

            modelBuilder.Entity("Food.Entity.AppRole", b =>
                {
                    b.HasBaseType("Microsoft.AspNetCore.Identity.IdentityRole");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("isDelete")
                        .HasColumnType("bit");

                    b.ToTable("Roles");

                    b.HasDiscriminator().HasValue("AppRole");

                    b.HasData(
                        new
                        {
                            Id = "f49e4348-718f-43e3-b1f6-6dc89c5Bb4fd",
                            ConcurrencyStamp = "67a8e46a-7ef5-4e8c-8903-00e85e258a62",
                            Name = "Staff",
                            NormalizedName = "staff",
                            Description = "Staff",
                            isDelete = false
                        },
                        new
                        {
                            Id = "360E601E-92F2-4F08-832B-604A21293258",
                            ConcurrencyStamp = "c8072e33-366c-405f-860e-63cb8dbba373",
                            Name = "Admin",
                            NormalizedName = "admin",
                            Description = "Admin",
                            isDelete = false
                        });
                });

            modelBuilder.Entity("Food.Entity.AppUser", b =>
                {
                    b.HasBaseType("Microsoft.AspNetCore.Identity.IdentityUser");

                    b.Property<DateTime>("DoB")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("bill_Address1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("bill_Address2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("bill_City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("bill_CompanyName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("bill_Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("bill_PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("bill_PostalCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("bill_State")
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("Users");

                    b.HasDiscriminator().HasValue("AppUser");

                    b.HasData(
                        new
                        {
                            Id = "DE544998-A3CC-4E12-ABB4-0642E57BD222",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "ebc36b25-a824-4a9b-9491-46e47475f1b7",
                            Email = "admin@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@GMAIL.COM",
                            NormalizedUserName = "ADMIN@GMAIL.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEHss7kXwPBJ0Gv7SGm023nUvZ4oSvZ2d4BxyPu1MumT/0pfE++GA//hgEJqKDj6V8Q==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "ee2f62e3-8705-4f49-8122-4fbac8aa8f78",
                            TwoFactorEnabled = false,
                            UserName = "Admin",
                            DoB = new DateTime(2020, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "admin",
                            LastName = "admin"
                        },
                        new
                        {
                            Id = "f49e4348-718f-43e3-b1f6-6dc89c5Bb5ff",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "f26026bf-f612-4827-b24f-ff51b22c00d0",
                            Email = "staff@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "STAFF@GMAIL.COM",
                            NormalizedUserName = "STAFF@GMAIL.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEFWyfb+rgceczhuu0zPbKejxBnCbTaHHnuAH3Mc2XP+2a/ECQWblSkdxFrYLHhTlsA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "23ec42bc-4744-445f-b1d1-2d02011d248c",
                            TwoFactorEnabled = false,
                            UserName = "Staff",
                            DoB = new DateTime(2020, 3, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "staff",
                            LastName = "staff"
                        });
                });

            modelBuilder.Entity("Food.Entity.Bills", b =>
                {
                    b.HasOne("Food.Entity.AppUser", "AppUserB")
                        .WithMany("BillsAU")
                        .HasForeignKey("bill_UserId");

                    b.Navigation("AppUserB");
                });

            modelBuilder.Entity("Food.Entity.Cart", b =>
                {
                    b.HasOne("Food.Entity.AppUser", "AppUserC")
                        .WithMany("CartU")
                        .HasForeignKey("cart_UserID");

                    b.Navigation("AppUserC");
                });

            modelBuilder.Entity("Food.Entity.CartsDevice", b =>
                {
                    b.HasOne("Food.Entity.Device", "DeviceCD")
                        .WithMany("CartsDeviceD")
                        .HasForeignKey("cartd_DeviceId");

                    b.Navigation("DeviceCD");
                });

            modelBuilder.Entity("Food.Entity.ProductInCart", b =>
                {
                    b.HasOne("Food.Entity.Cart", "CartPICart")
                        .WithMany("ProductInCartC")
                        .HasForeignKey("pic_CartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Food.Entity.Products", "ProductsPICart")
                        .WithMany("ProductInCartP")
                        .HasForeignKey("pic_ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CartPICart");

                    b.Navigation("ProductsPICart");
                });

            modelBuilder.Entity("Food.Entity.ProductInCartDevices", b =>
                {
                    b.HasOne("Food.Entity.CartsDevice", "CartsDevicePICD")
                        .WithMany("ProductInCartDevicesCD")
                        .HasForeignKey("picd_CartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Food.Entity.Products", "ProductsPICD")
                        .WithMany("ProductInCartDevicesP")
                        .HasForeignKey("picd_ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CartsDevicePICD");

                    b.Navigation("ProductsPICD");
                });

            modelBuilder.Entity("Food.Entity.ProductsInCategories", b =>
                {
                    b.HasOne("Food.Entity.Categories", "CategoriesPIC")
                        .WithMany("ProductsInCategoriesC")
                        .HasForeignKey("pic_CategoriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Food.Entity.Products", "ProductsPIC")
                        .WithMany("ProductsInCategoriesP")
                        .HasForeignKey("pic_productId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CategoriesPIC");

                    b.Navigation("ProductsPIC");
                });

            modelBuilder.Entity("Food.Entity.ReviewInproduct", b =>
                {
                    b.HasOne("Food.Entity.Products", "ProductsRIP")
                        .WithMany("ReviewInproductP")
                        .HasForeignKey("rip_ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Food.Entity.Reviews", "ReviewsRIP")
                        .WithMany("ReviewInproductR")
                        .HasForeignKey("rip_ReviewId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProductsRIP");

                    b.Navigation("ReviewsRIP");
                });

            modelBuilder.Entity("Food.Entity.Reviews", b =>
                {
                    b.HasOne("Food.Entity.AppUser", "AppUserR")
                        .WithMany("ReviewsU")
                        .HasForeignKey("review_UserId");

                    b.Navigation("AppUserR");
                });

            modelBuilder.Entity("Food.Entity.SubReview", b =>
                {
                    b.HasOne("Food.Entity.AppUser", "AppUserSR")
                        .WithMany("SubReviewSR")
                        .HasForeignKey("subReview_UserId");

                    b.Navigation("AppUserSR");
                });

            modelBuilder.Entity("Food.Entity.SubReviewInReview", b =>
                {
                    b.HasOne("Food.Entity.Reviews", "Reviews")
                        .WithMany("SubReviewInReview")
                        .HasForeignKey("SRiR_ReviewId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Food.Entity.SubReview", "SubReview")
                        .WithMany("SubReviewInReview")
                        .HasForeignKey("SRiR_SubReviewId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Reviews");

                    b.Navigation("SubReview");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Food.Entity.Cart", b =>
                {
                    b.Navigation("ProductInCartC");
                });

            modelBuilder.Entity("Food.Entity.CartsDevice", b =>
                {
                    b.Navigation("ProductInCartDevicesCD");
                });

            modelBuilder.Entity("Food.Entity.Categories", b =>
                {
                    b.Navigation("ProductsInCategoriesC");
                });

            modelBuilder.Entity("Food.Entity.Device", b =>
                {
                    b.Navigation("CartsDeviceD");
                });

            modelBuilder.Entity("Food.Entity.Products", b =>
                {
                    b.Navigation("ProductInCartDevicesP");

                    b.Navigation("ProductInCartP");

                    b.Navigation("ProductsInCategoriesP");

                    b.Navigation("ReviewInproductP");
                });

            modelBuilder.Entity("Food.Entity.Reviews", b =>
                {
                    b.Navigation("ReviewInproductR");

                    b.Navigation("SubReviewInReview");
                });

            modelBuilder.Entity("Food.Entity.SubReview", b =>
                {
                    b.Navigation("SubReviewInReview");
                });

            modelBuilder.Entity("Food.Entity.AppUser", b =>
                {
                    b.Navigation("BillsAU");

                    b.Navigation("CartU");

                    b.Navigation("ReviewsU");

                    b.Navigation("SubReviewSR");
                });
#pragma warning restore 612, 618
        }
    }
}
